module.exports = [
  {
    title: "Cozy Mountain Cabin",
    description: "A beautiful cabin in the mountains with stunning views.",
    price: 150,
    image: {
      filename: "cozy_mountain_cabin.jpg",
      url: "https://www.cozymountaincabins.com/wp-content/uploads/2021/09/web_CMC_2021_Updates-59-640x437.jpg",
    },
    location: "Aspen, Colorado",
    country: "USA",
  },
  {
    title: "Modern City Apartment",
    description: "A luxurious apartment in the heart of the city.",
    price: 200,
    image: {
      filename: "modern_city_apartment.jpg",
      url: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/563197815.jpg?k=aca27153567b89c5bf21ba139e9d385fb8b92ed8eda63c8c9c9e9d3d1b56cf82&o=&hp=1",
    },
    location: "New York City, NY",
    country: "USA",
  },
  {
    title: "Beachfront Bungalow",
    description: "A serene bungalow with direct access to the beach.",
    price: 180,
    image: {
      filename: "beachfront_bungalow.jpg",
      url: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/296107312.jpg?k=6453006748d7625ba9d4d9ba14f766d9dabc7bece921c09c69bae915c616babf&o=&hp=1",
    },
    location: "Malibu, California",
    country: "USA",
  },
  {
    title: "Rustic Countryside Cottage",
    description: "A peaceful retreat in the countryside.",
    price: 120,
    image: {
      filename: "rustic_countryside_cottage.jpg",
      url: "https://images.stockcake.com/public/a/5/3/a5371eaf-d470-4a3d-b46f-8ec3914d75ff_large/rustic-countryside-home-stockcake.jpg",
    },
    location: "Yorkshire, England",
    country: "UK",
  },
  {
    title: "Luxury Villa with Pool",
    description: "A spacious villa with a private swimming pool.",
    price: 350,
    image: {
      filename: "luxury_villa_pool.jpg",
      url: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/143896241.jpg?k=dc96cf926a551b70653da8551f93bdaf7ee8399287b7acbedf6c4be66446b777&o=&hp=1",
    },
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Tropical Treehouse",
    description: "A unique stay in a treehouse surrounded by nature.",
    price: 90,
    image: {
      filename: "tropical_treehouse.jpg",
      url: "https://onekindesign.com/wp-content/uploads/2016/12/Luxury-Vacation-Home-Treehouse-Mexico-01-1-Kindesign.jpg",
    },
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Ski Lodge in the Alps",
    description: "A cozy ski lodge perfect for winter vacations.",
    price: 300,
    image: {
      filename: "ski_lodge_alps.jpg",
      url: "https://dam.mediacorp.sg/image/upload/s--IA_31faj--/c_crop,h_745,w_1324,x_0,y_755/c_fill,g_auto,h_676,w_1200/f_auto,q_auto/v1/mediacorp/cna/image/2023/02/24/Skiing-in-the-Alps.jpg?itok=IESRPeUa",
    },
    location: "Swiss Alps",
    country: "Switzerland",
  },
  {
    title: "Modern Studio Apartment",
    description: "A compact yet stylish studio apartment.",
    price: 130,
    image: {
      filename: "modern_studio_apartment.jpg",
      url: "https://i.pinimg.com/736x/f0/57/63/f05763d99e4e728d1e56e8fc4d0c48cd.jpg",
    },
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Desert Glamping Tent",
    description: "Luxury camping experience in the desert.",
    price: 170,
    image: {
      filename: "desert_glamping_tent.jpg",
      url: "https://media.glampinghub.com/CACHE/images/accommodations/erg-chigaga-luxury-desert-lodge-agafay-luxury-camp-tent-1517303217020/3612a260a025754dc164cd815f00f78f.jpg",
    },
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Hillside Wooden Cabin",
    description: "A charming wooden cabin with breathtaking views.",
    price: 140,
    image: {
      filename: "hillside_wooden_cabin.jpg",
      url: "https://coventryloghomes.com/wp-content/uploads/2020/04/CustomHillside-15-scaled.jpg",
    },
    location: "Lake Tahoe",
    country: "USA",
  },
  {
    title: "Secluded Island Retreat",
    description: "A private island getaway for ultimate relaxation.",
    price: 500,
    image: {
      filename: "secluded_island_retreat.jpg",
      url: "https://destinationdeluxe.com/wp-content/uploads/2021/03/Gladden-Private-Island-Destination-Deluxe.jpg",
    },
    location: "Maldives",
    country: "Maldives",
  },
  {
    title: "Historic Castle Stay",
    description: "Live like royalty in a historic castle.",
    price: 400,
    image: {
      filename: "historic_castle_stay.jpg",
      url: "https://www.historic-uk.com/wp-content/uploads/2024/02/sneaton-cast-768x405.jpg",
    },
    location: "Edinburgh",
    country: "Scotland",
  },
  {
    title: "Eco-Friendly Earth House",
    description: "A sustainable house built with eco-friendly materials.",
    price: 160,
    image: {
      filename: "eco_friendly_earth_house.jpg",
      url: "https://res.cloudinary.com/larq/w_1440,h_960,c_fit/auto-mapping-folder/2020/04/bali-eco-home.jpg",
    },
    location: "Costa Rica",
    country: "Costa Rica",
  },
  {
    title: "Charming Boathouse",
    description: "A cozy boathouse with stunning waterfront views.",
    price: 250,
    image: {
      filename: "charming_boathouse.jpg",
      url: "https://a0.muscache.com/im/pictures/miso/Hosting-733167863751951676/original/6e70c49d-fbb2-424c-a81e-b428acc4b4b5.jpeg?im_w=720&im_format=avif",
    },
    location: "Amsterdam",
    country: "Netherlands",
  },
];
